## Exercício 1

#### Implemente os algoritmos de substituição direta e retroativa para solução de sistemas lineares da forma triangular inferior e superior, respectivamente.

Algoritmo de substituição direta para solução de sistemas lineares da forma triangular inferior:

In [109]:
import numpy as np

In [110]:
# A é uma matriz quadrada nxn
# b é um vetor coluna nx1
# queremos encontrar x (o vetor coluna nx1) tal que Ax = b
def substituicao_direta(A,b):
    n = len(A)
    x = np.zeros([n, 1])
    
    # Passo 1: Calcule x1 = b1/a11
    x[0,0] = b[0,0]/A[0,0]
    
    # Passo 2: Para i = 2 : n, calcule xi
    for i in range(1,n):
        somatorio = 0
        for j in range(i):
            somatorio = somatorio + A[i,j]*x[j,0]
        x[i,0] = (b[i,0] - somatorio)/A[i,i]
    return x

#### Teste 1

In [111]:
A = np.matrix([[1,0,0], [1,2,0], [1,2,3]])
b = np.matrix([[4], [5], [6]])
A, b

(matrix([[1, 0, 0],
         [1, 2, 0],
         [1, 2, 3]]),
 matrix([[4],
         [5],
         [6]]))

In [112]:
x = substituicao_direta(A,b)
x

array([[4.        ],
       [0.5       ],
       [0.33333333]])

In [113]:
A*x

matrix([[4.],
        [5.],
        [6.]])

#### Teste 2

In [114]:
A = np.matrix([[4,0,0], [-2,5,0], [1,7,3]])
b = np.matrix([[-2], [5], [6]])
A, b

(matrix([[ 4,  0,  0],
         [-2,  5,  0],
         [ 1,  7,  3]]),
 matrix([[-2],
         [ 5],
         [ 6]]))

In [115]:
x = substituicao_direta(A,b)
x

array([[-0.5],
       [ 0.8],
       [ 0.3]])

In [116]:
A * x

matrix([[-2.],
        [ 5.],
        [ 6.]])

Algoritmo de substituição retroativa para solução de sistemas lineares da forma triangular superior:

In [117]:
# A é uma matriz quadrada nxn
# b é um vetor coluna nx1
# queremos encontrar x (o vetor coluna nx1) tal que Ax = b
def substituicao_retroativa(A,b):
    n = len(A)
    x = np.zeros([n, 1])
    
    # Passo 1: Calcule x1 = b1/a11
    x[n-1,0] = b[n-1,0]/A[n-1,n-1]
    
    # Passo 2: Para i = n − 1 : 1, calcule xi
    for i in reversed(range(n-1)):
        somatorio = 0
        for j in range(i+1,n):
            somatorio = somatorio + A[i,j]*x[j,0]
        x[i,0] = (b[i,0] - somatorio)/A[i,i]
    return x

#### Teste 1

In [118]:
A = np.matrix([[3,2], [0,2]])
b = np.matrix([[5], [2]])
A, b

(matrix([[3, 2],
         [0, 2]]),
 matrix([[5],
         [2]]))

In [119]:
x = substituicao_retroativa(A,b)
x

array([[1.],
       [1.]])

In [120]:
A*x

matrix([[5.],
        [2.]])

#### Teste 2

In [121]:
A = np.matrix([[3,1,1,1], [0,1.6667, 0.6667, 1.6667], [0, 0, 0.4, 0], [0, 0, 0, -1.0001]])
b = np.matrix([[6], [4.0002], [0.4001], [-1.0003]])
A, b

(matrix([[ 3.    ,  1.    ,  1.    ,  1.    ],
         [ 0.    ,  1.6667,  0.6667,  1.6667],
         [ 0.    ,  0.    ,  0.4   ,  0.    ],
         [ 0.    ,  0.    ,  0.    , -1.0001]]),
 matrix([[ 6.    ],
         [ 4.0002],
         [ 0.4001],
         [-1.0003]]))

In [122]:
x = substituicao_retroativa(A,b)
x

array([[0.99993   ],
       [0.99976002],
       [1.00025   ],
       [1.00019998]])

In [123]:
A*x

matrix([[ 6.    ],
        [ 4.0002],
        [ 0.4001],
        [-1.0003]])

## Exercício 7

#### a) Escreva uma função fatoracaoLU(A) que recebe uma matriz $A\in R_{n×n}$ e retorna os fatores L e U da fatoração LU de A

In [138]:
def fatoracaoLU(A):
    # Passo 0. Defina lii = 1 para i = 1, . . . , n, lij = 0 para todo i < j, e uij = 0 para todo i > j.
    n = len(A)
    L = np.eye(n,n)
    U = np.zeros([n,n])
    
    #Passo 1. Defina u1j = a1j para j = 1, . . . , n.
    for j in range(n):
        U[0,j] = A[0,j]
        
    # Passo 2. Calcule li1 = ai1/u11 para i = 2, . . . , n.
    for i in range(1, n):
        L[i,0] = A[i,0]/U[0,0]
        
    # Passo 3. Para p = 2, . . . , n, calcule upj
    for p in range(1,n):
        for j in range(p,n):
            somatorio = 0
            for k in range(p):
                somatorio = somatorio + L[p,k]*U[k,j]
            U[p,j] = A[p,j] - somatorio
        if p<n:
            for i in range(p+1,n):
                somatorio = 0
                for k in range(p):
                    somatorio = somatorio + L[i,k]*U[k,p]
                L[i,p] = (A[i,p] - somatorio)/U[p,p]
    return L,U

#### Teste 1

In [148]:
A = np.matrix([[3,2,4], [1,1,2], [4,3,-2]])
A

matrix([[ 3,  2,  4],
        [ 1,  1,  2],
        [ 4,  3, -2]])

In [149]:
L,U = fatoracaoLU(A)
L,U

(array([[1.        , 0.        , 0.        ],
        [0.33333333, 1.        , 0.        ],
        [1.33333333, 1.        , 1.        ]]),
 array([[ 3.        ,  2.        ,  4.        ],
        [ 0.        ,  0.33333333,  0.66666667],
        [ 0.        ,  0.        , -8.        ]]))

In [150]:
np.dot(L,U)

array([[ 3.,  2.,  4.],
       [ 1.,  1.,  2.],
       [ 4.,  3., -2.]])

#### Teste 2

In [151]:
B = np.matrix([[1,2,1], [2,-3,-1], [3,-1,-2]])
B

matrix([[ 1,  2,  1],
        [ 2, -3, -1],
        [ 3, -1, -2]])

In [154]:
L, U = fatoracaoLU(B)
L, U

(array([[1., 0., 0.],
        [2., 1., 0.],
        [3., 1., 1.]]),
 array([[ 1.,  2.,  1.],
        [ 0., -7., -3.],
        [ 0.,  0., -2.]]))

In [155]:
np.dot(L,U)

array([[ 1.,  2.,  1.],
       [ 2., -3., -1.],
       [ 3., -1., -2.]])

#### b) Usando o código do item (a), escreva uma função sistemaLinear1(A, b) que recebe uma matriz $A\in R_{nxn}$ não-singular e um vetor $b\in R^{n}$, e retorna a solução x do sistema linear Ax = b.

In [156]:
def sistemaLinear1(A, b):
    L,U = fatoracaoLU(A)
    # Passo 1. Resolva o sistema triangular inferior Ly = b.
    y = substituicao_direta(L,b)
    # Passo 2. Resolva o sistema triangular superior Ux = y.
    x = substituicao_retroativa(U,y)
    return x

#### c) Usando os códigos dos itens (a) e (b), calcule a fatoração LU da matriz A = [[1 2 1], [2 7 6], [3 18 27]] e resolva o sistema linear Ax = b com $b = [4, 15, 18]^{T}$

In [164]:
A = np.array([[1, 2, 1], [2, 7, 6], [3, 18, 27]])
b = np.array([[4], [15], [18]])

Calculando a fatoração LU da matriz A:

In [161]:
L,U = fatoracaoLU(A)
L,U

(array([[1., 0., 0.],
        [2., 1., 0.],
        [3., 4., 1.]]),
 array([[1., 2., 1.],
        [0., 3., 4.],
        [0., 0., 8.]]))

In [168]:
# prova real
np.dot(L,U)

array([[ 1.,  2.,  1.],
       [ 2.,  7.,  6.],
       [ 3., 18., 27.]])

Resolvendo o sistema linear $Ax = b$ com $𝑏=[4,15,18]^{T}$ 

In [166]:
x = sistemaLinear1(A, b)
x

array([[-5.25],
       [ 6.  ],
       [-2.75]])

In [167]:
# prova real
np.dot(A,x)

array([[ 4.],
       [15.],
       [18.]])

## Exercício 10

#### a) Escreva uma função $[G] = fatoracaoCholesky(A)$ que recebe uma matriz $A\in R_{nxn}$ e retorna $G$ triangular inferior tal que $A = GG^{T}$

In [179]:
def fatoracaoCholesky(A):
    n = len(A)
    G = np.zeros([n,n])
    # Passo 0. Calcule g11 = √a11 e gi1 = ai1/g11 para i = 2, . . . , n.
    G[0,0] = A[0,0]**(1/2)
    for i in range(1,n):
        G[i,0] = A[i,0]/G[0,0]
        
    # Passo 1. Para k = 2, . . . , n:
    for k in range(1,n):
        # calcule gkk
        somatorio = 0
        for j in range(k):
            somatorio = somatorio + G[k,j]**2
        G[k,k] = (A[k,k] - somatorio)**(1/2)
        
        # Para i = (k + 1), . . . , n, calcule
        for i in range(k+1,n):
            somatorio = 0
            for j in range(k):
                somatorio = somatorio + G[i,j]*G[k,j]
            G[i,k] = (A[i,k] - somatorio)/G[k,k]
    return G

#### Teste 1

In [188]:
A = np.array([[4, 12, -16], [12, 37, -43], [-16, -43, 98]])
A

array([[  4,  12, -16],
       [ 12,  37, -43],
       [-16, -43,  98]])

In [189]:
G = fatoracaoCholesky(A)
G

array([[ 2.,  0.,  0.],
       [ 6.,  1.,  0.],
       [-8.,  5.,  3.]])

In [190]:
GT = np.transpose(G)
GT

array([[ 2.,  6., -8.],
       [ 0.,  1.,  5.],
       [ 0.,  0.,  3.]])

In [192]:
# prova real
np.dot(G,GT)

array([[  4.,  12., -16.],
       [ 12.,  37., -43.],
       [-16., -43.,  98.]])

#### Lista 2

In [193]:
B = np.array([[9, -6, 3], [-6, 29, -7], [3, -7, 18]])
B

array([[ 9, -6,  3],
       [-6, 29, -7],
       [ 3, -7, 18]])

In [194]:
G = fatoracaoCholesky(B)
G

array([[ 3.,  0.,  0.],
       [-2.,  5.,  0.],
       [ 1., -1.,  4.]])

In [196]:
GT = np.transpose(G)
GT

array([[ 3., -2.,  1.],
       [ 0.,  5., -1.],
       [ 0.,  0.,  4.]])

In [197]:
# prova real
np.dot(G,GT)

array([[ 9., -6.,  3.],
       [-6., 29., -7.],
       [ 3., -7., 18.]])

#### b) Usando o código do item (a), escreva uma função $[x] = sistemaLinear2(A, b)$ que recebe uma matriz $A\in R_{nxn}$ simétrica positiva definida e um vetor $b\in R^{n}$ e retorna a solução $x$ do sistema linear $Ax = b$.

In [199]:
def sistemaLinear2(A,b):
    # G(GTx) = b
    G = fatoracaoCholesky(A)
    GT = np.transpose(G)
    
    # Gy = b 
    y = substituicao_direta(G,b)
    
    # GTx = y
    x = substituicao_retroativa(GT, y)
    return x

#### c) Usando os códigos dos itens (a) e (b), calcule a fatoração de Cholesky da matriz A = [[1, 7, 12], [7, 53, 90], [12, 90, 162]] e resolva o sistema linear $Ax = b$ com $b = [51, 383, 678]^{T}$

In [209]:
A = np.array([[1, 7, 12], [7, 53, 90], [12, 90, 162]])
b = np.array([[51],[383],[678]])
A,b

(array([[  1,   7,  12],
        [  7,  53,  90],
        [ 12,  90, 162]]),
 array([[ 51],
        [383],
        [678]]))

Fatoração de Cholesky da matriz A:

In [205]:
C = fatoracaoCholesky(A)
C

array([[ 1.,  0.,  0.],
       [ 7.,  2.,  0.],
       [12.,  3.,  3.]])

In [206]:
# prova real
np.dot(C, np.transpose(C))

array([[  1.,   7.,  12.],
       [  7.,  53.,  90.],
       [ 12.,  90., 162.]])

Solução do sistema linear $Ax = b$ com $b = [51, 383, 678]^{T}$

In [211]:
x = sistemaLinear2(A,b)
x

array([[1.],
       [2.],
       [3.]])

In [212]:
# prova real
np.dot(A,x)

array([[ 51.],
       [383.],
       [678.]])