# Lista 2 - Álgebra Linear Aplicada - PPGM UFPR

#### Nome: Gustavo Rodrigues da Silva

#### Instruções: 
Para que o notebook funcione corretamente, basta ter o pacote numpy instalado e compilar as células sequencialmente - de cima para baixo.

In [1]:
# a biblioteca numpy foi importada para auxiliar na criação e operação com matrizes
import numpy as np

## Exercício 6

#### b) Implemente o processo de ortogonalização de Gram-Schmidt. Usando esse código, escreva uma função que calcule a fatoração $QR$ incompleta de uma matriz $A\in\mathbb{R}^{m×n}$ com $m\geq n$.

Primeiro, será feita a função gram_schmidt( ) para implementar o processo de ortogonalização de Gram-Schmidt:

In [2]:
def gram_schmidt(V):
    m,n = V.shape
    W = np.zeros([m, n])
    
    # Passo 0. w_1 = v_1
    W[:,0] = V[:,0]
    
    # Passo 1. para i=2,...,n calcule os w_i
    for i in range(1,n):
        somatorio = np.zeros(m)
        for j in range(i):
            somatorio = somatorio + (np.dot(V[:,i],W[:,j])/np.dot(W[:,j],W[:,j]))*W[:,j]
        W[:,i] = V[:,i] - somatorio
    return W

#### Teste

In [61]:
A = np.array([[-1,-1,1],[1,3,3],[-1,-1,5],[1,3,7]])
A

array([[-1, -1,  1],
       [ 1,  3,  3],
       [-1, -1,  5],
       [ 1,  3,  7]])

In [62]:
W = gram_schmidt(A)
W

array([[-1.,  1., -2.],
       [ 1.,  1., -2.],
       [-1.,  1.,  2.],
       [ 1.,  1.,  2.]])

Note que o conjunto das colunas de $W$ é ortogonal, pois as colunas são ortogonais entre si, como pode-se ver:

In [55]:
np.dot(W[:,0],W[:,1])

0.0

In [57]:
np.dot(W[:,0],W[:,2])

0.0

In [58]:
np.dot(W[:,1],W[:,2])

0.0

Agora, será usada a função gram_schmidt( ) para construir a função QR_incompleta( ), que calcula a fatoração QR incompleta de uma matriz

In [3]:
def QR_incompleta(A):
    W = gram_schmidt(A)
    m,n = A.shape
    Q = np.zeros([m,n])
    R = np.zeros([n,n])
    for j in range(n):
        Q[:,j] = W[:,j]/(np.dot(W[:,j],W[:,j]))**(1/2)
        for i in range(j+1):
            R[i,j] = np.dot(A[:,j], Q[:,i])
    return Q,R

#### c) Com sua função, calcule uma fatoração QR incompleta da matriz $A = np.array([[-1,-1,1],[1,3,3],[-1,-1,5],[1,3,7]])$

In [73]:
A

array([[-1, -1,  1],
       [ 1,  3,  3],
       [-1, -1,  5],
       [ 1,  3,  7]])

In [66]:
Q,R = QR_incompleta(A)
Q,R

(array([[-0.5,  0.5, -0.5],
        [ 0.5,  0.5, -0.5],
        [-0.5,  0.5,  0.5],
        [ 0.5,  0.5,  0.5]]),
 array([[2., 4., 2.],
        [0., 2., 8.],
        [0., 0., 4.]]))

Note que o resultado obtido está correto. A matriz $R$ é triangular superior e $Q$ é ortonormal, pois:

In [76]:
# as colunas de Q são ortogonais:
np.dot(Q[:,0],Q[:,1]), np.dot(Q[:,0],Q[:,2]), np.dot(Q[:,1],Q[:,2])

(0.0, 0.0, 0.0)

In [78]:
# as colunas de Q são ortonormais:
(np.dot(Q[:,0], Q[:,0]))**(1/2), (np.dot(Q[:,1], Q[:,1]))**(1/2), (np.dot(Q[:,2], Q[:,2]))**(1/2)

(1.0, 1.0, 1.0)

Além disso, vemos que $QR = A$:

In [80]:
np.dot(Q,R), np.dot(Q,R) == A

(array([[-1., -1.,  1.],
        [ 1.,  3.,  3.],
        [-1., -1.,  5.],
        [ 1.,  3.,  7.]]),
 array([[ True,  True,  True],
        [ True,  True,  True],
        [ True,  True,  True],
        [ True,  True,  True]]))

## Exercício 10

Usaremos a função que resolve um sistema triangular superior, feita como exercício na lista 1:

In [12]:
# A é uma matriz quadrada nxn
# b é um vetor coluna nx1
# queremos encontrar x (o vetor coluna nx1) tal que Ax = b
def substituicao_retroativa(A,b):
    n = len(A)
    x = np.zeros([n, 1])
    
    # Passo 1: Calcule x1 = b1/a11
    x[n-1,0] = b[n-1,0]/A[n-1,n-1]
    
    # Passo 2: Para i = n − 1 : 1, calcule xi
    for i in reversed(range(n-1)):
        somatorio = 0
        for j in range(i+1,n):
            somatorio = somatorio + A[i,j]*x[j,0]
        x[i,0] = (b[i,0] - somatorio)/A[i,i]
    return x

#### a) Para cada usuário, estime as pontuações $y^{(f)}$ dos filmes não assistidos com base no modelo de regressão linear
#### $$y = \theta_0 + \theta_1x_1 + \theta_2x_2$$
#### Descreva o problema de mínimos quadrados linear correspondente e obtenha os coeficientes acima usando seus códigos.

------------------ Carol ------------------

In [14]:
A_carol = np.array([[1, 0.1, 1], [1, 0.8, 0.2], [1, 0.6, 0.4], [1, 1, 0.2], [1, 0.9, 0.1]])
b_carol = np.array([[4],[4],[2.5],[1],[3.5]])
A_carol, b_carol

(array([[1. , 0.1, 1. ],
        [1. , 0.8, 0.2],
        [1. , 0.6, 0.4],
        [1. , 1. , 0.2],
        [1. , 0.9, 0.1]]),
 array([[4. ],
        [4. ],
        [2.5],
        [1. ],
        [3.5]]))

In [15]:
Q_carol,R_carol = QR_incompleta(A_carol)
Q_carol,R_carol

(array([[ 0.4472136 , -0.81375962,  0.26219214],
        [ 0.4472136 ,  0.16836406, -0.34371407],
        [ 0.4472136 , -0.11224271, -0.3304943 ],
        [ 0.4472136 ,  0.44897083,  0.76234019],
        [ 0.4472136 ,  0.30866744, -0.35032396]]),
 array([[ 2.23606798,  1.52052622,  0.84970583],
        [ 0.        ,  0.71274119, -0.70432298],
        [ 0.        ,  0.        ,  0.17868725]]))

Queremos resolver o sistema triangular superior $Rx = Q^Tb$ usando $substituicao\_retroativa(R,Q^Tb)$:

In [19]:
substituicao_retroativa(R_carol,np.dot(Q_carol.T,b_carol))

array([[ 13.78606658],
       [-10.80764488],
       [ -9.04438964]])

Uma forma razoável de verificar se os coeficientes obtidos fazem sentido é analisando o comportamento das previsões no conjunto de treinamento. Para tal, vejamos o que o modelo de regressão linear obtido prevê para as pontuações conhecidas da Carol:

In [83]:
y_pred = np.zeros([5,1])

In [84]:
# The Notebook
y_pred[0] = 13.78606658 -10.80764488*0.1 -9.04438964*1
y_pred[0]

array([3.66091245])

In [85]:
# Whiplash
y_pred[1] = 13.78606658 -10.80764488*0.8 -9.04438964*0.2
y_pred[1]

array([3.33107275])

In [86]:
# Os Miseráveis
y_pred[2] = 13.78606658 -10.80764488*0.6 -9.04438964*0.4
y_pred[2]

array([3.6837238])

In [87]:
# Rocky I
y_pred[3] = 13.78606658 -10.80764488*1 -9.04438964*0.2
y_pred[3]

array([1.16954377])

In [88]:
# Toy Story 3
y_pred[4] = 13.78606658 -10.80764488*0.9 -9.04438964*0.1
y_pred[4]

array([3.15474722])

Note que as previsões fazem sentido no conjunto de teste. Podemos ver a diferença entre as notas dadas pela Carol (vetor $b\_carol$) e as previsões para as respectivas notas (vetor $y\_pred$):

In [89]:
b_carol, y_pred

(array([[4. ],
        [4. ],
        [2.5],
        [1. ],
        [3.5]]),
 array([[3.66091245],
        [3.33107275],
        [3.6837238 ],
        [1.16954377],
        [3.15474722]]))

Apesar de não fornecer resultados precisos, o modelo está funcionando. Portanto, uma previsão para a pontuação que a Carol daria para o filme "Os 8 odiados", cujo $x_1=1$ e $x_2=0$, é dada por:
$$y = \theta_0 + \theta_1x_1 + \theta_2x_2$$

In [22]:
y_carol = 13.78606658 -10.80764488*1 -9.04438964*0
y_carol

2.9784217

------------------ Lorayne ------------------

In [23]:
A_lorayne = np.array([[1, 0.1, 1], [1, 0.8, 0.2], [1, 0.9, 0.1]])
b_lorayne = np.array([[4],[4.5],[5]])
A_lorayne, b_lorayne

(array([[1. , 0.1, 1. ],
        [1. , 0.8, 0.2],
        [1. , 0.9, 0.1]]),
 array([[4. ],
        [4.5],
        [5. ]]))

In [24]:
Q_lorayne,R_lorayne = QR_incompleta(A_lorayne)
Q_lorayne,R_lorayne

(array([[ 0.57735027, -0.81110711,  0.09365858],
        [ 0.57735027,  0.32444284, -0.74926865],
        [ 0.57735027,  0.48666426,  0.65561007]]),
 array([[ 1.73205081,  1.03923048,  0.75055535],
        [ 0.        ,  0.6164414 , -0.69755211],
        [ 0.        ,  0.        ,  0.00936586]]))

In [26]:
substituicao_retroativa(R_lorayne,np.dot(Q_lorayne.T,b_lorayne))

array([[-29.5],
       [ 35. ],
       [ 30. ]])

In [27]:
# Os Oito Odiados
-29.5 + 35*1 + 30*0

5.5

In [28]:
# Os Miseráveis
-29.5 + 35*0.6 + 30*0.4

3.5

In [29]:
# Rocky I
-29.5 + 35*1 + 30*0.2

11.5

------------------ Wilian ------------------

In [36]:
A_wilian = np.array([[1, 1, 0], [1, 1, 0.2], [1, 0.9, 0.1]])
b_wilian = np.array([[4.5],[3.5],[3]])
A_wilian, b_wilian

(array([[1. , 1. , 0. ],
        [1. , 1. , 0.2],
        [1. , 0.9, 0.1]]),
 array([[4.5],
        [3.5],
        [3. ]]))

In [37]:
Q_wilian,R_wilian = QR_incompleta(A_wilian)
Q_wilian,R_wilian

(array([[ 5.77350269e-01,  4.08248290e-01, -7.07106781e-01],
        [ 5.77350269e-01,  4.08248290e-01,  7.07106781e-01],
        [ 5.77350269e-01, -8.16496581e-01, -9.81307787e-17]]),
 array([[1.73205081, 1.67431578, 0.17320508],
        [0.        , 0.08164966, 0.        ],
        [0.        , 0.        , 0.14142136]]))

In [38]:
substituicao_retroativa(R_wilian,np.dot(Q_wilian.T,b_wilian))

array([[-5.5],
       [10. ],
       [-5. ]])

In [42]:
# The Notebook
-5.5 + 10*0.1 -5*1

-9.5

In [43]:
# Whiplash
-5.5 + 10*0.8 -5*0.2

1.5

In [41]:
# Os Miseráveis

In [44]:
-5.5 + 10*0.6 -5*0.4

-1.5

------------------ Manu ------------------

In [48]:
A_manu = np.array([[1, 0.6, 0.4], [1, 1, 0.2], [1, 0.9, 0.1]])
b_manu = np.array([[5],[4.5],[5]])
A_manu, b_manu

(array([[1. , 0.6, 0.4],
        [1. , 1. , 0.2],
        [1. , 0.9, 0.1]]),
 array([[5. ],
        [4.5],
        [5. ]]))

In [49]:
Q_manu,R_manu = QR_incompleta(A_manu)
Q_manu,R_manu

(array([[ 0.57735027, -0.79259392,  0.19611614],
        [ 0.57735027,  0.56613852,  0.58834841],
        [ 0.57735027,  0.22645541, -0.78446454]]),
 array([[ 1.73205081,  1.44337567,  0.40414519],
        [ 0.        ,  0.29439203, -0.18116433],
        [ 0.        ,  0.        ,  0.11766968]]))

In [51]:
substituicao_retroativa(R_manu,np.dot(Q_manu.T,b_manu))

array([[ 7.5],
       [-2.5],
       [-2.5]])

In [55]:
# The Notebook
7.5 -2.5*0.1 -2.5*1

4.75

In [56]:
# Whiplash
7.5 -2.5*0.8 -2.5*0.2

5.0

In [57]:
# Os Oito Odiados
7.5 -2.5*1 -2.5*0

5.0

------------------ Thayse ------------------

In [59]:
A_thayse = np.array([[1, 0.1, 1], [1, 0.8, 0.2], [1, 1, 0], [1, 1, 0.2], [1, 0.9, 0.1]])
b_thayse = np.array([[3.5],[4.5],[5],[5],[5]])
A_thayse, b_thayse

(array([[1. , 0.1, 1. ],
        [1. , 0.8, 0.2],
        [1. , 1. , 0. ],
        [1. , 1. , 0.2],
        [1. , 0.9, 0.1]]),
 array([[3.5],
        [4.5],
        [5. ],
        [5. ],
        [5. ]]))

In [60]:
Q_thayse,R_thayse = QR_incompleta(A_thayse)
Q_thayse,R_thayse

(array([[ 0.4472136 , -0.87266171,  0.10846755],
        [ 0.4472136 ,  0.05288859, -0.33131906],
        [ 0.4472136 ,  0.31733153, -0.29582059],
        [ 0.4472136 ,  0.31733153,  0.83224192],
        [ 0.4472136 ,  0.18511006, -0.31356982]]),
 array([[ 2.23606798,  1.69941166,  0.67082039],
        [ 0.        ,  0.75630682, -0.78010668],
        [ 0.        ,  0.        ,  0.17729514]]))

In [62]:
substituicao_retroativa(R_thayse,np.dot(Q_thayse.T,b_thayse))

array([[3.29310345],
       [1.71301446],
       [0.01668521]])

In [63]:
# Os Miseráveis
3.29310345 + 1.71301446*0.6 + 0.01668521*0.4

4.32758621